apiVersion: v1
kind: Service
metadata:
    name: "nick8s-7dc3"
    labels:
        app: "nick8s-7dc3"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "nick8s-7dc3"